server:
  port: 8002

spring:
  application:
    name: user
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:7000/eureka/                 #设置服务注册中心地址
  instance:
    hostname: localhost