server:
  port: 8003

spring:
  application:
    name: document
  data:
    mongodb:
      database: markdown
      host: 120.25.207.78
  #      host: 175.178.147.9
  #      username: root
  #      password: torch
  #      port: 27017
  #      authentication-database: admin
  redis:
    host: 175.178.147.9
    port: 6379
    password: torch

eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:7000/eureka/                 #设置服务注册中心地址
  instance:
    hostname: localhost

ribbon:
  ConnectTimeout: 5000             #设置连接超时时间,默认为1s
  ReadTimeout: 5000                #设置读取超时时间
  OkToRetryOnAllOperations: true   # 对所有操作请求都进行重试
  MaxAutoRetries: 1                # 对当前实例的重试次数
  MaxAutoRetriesNextServer: 2      # 切换实例的重试次数

logging:
  level:
    com.itheima.eurekafeignclient.service.FeignService: DEBUG

feign:
  circuitbreaker:
    enabled: true