server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true          #开启动态路由，利用微服务名来进行路由
      routes:
        - id: login
          uri: lb://user
          predicates:
            - Path=/login/**

        - id: doc
          uri: lb://document
          predicates:
            - Path=/doc/**

eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:7000/eureka/                 #设置服务注册中心地址
  instance:
    hostname: localhost

